// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgkidivyaoutauiwkzig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1na2lkaXZ5YW91dGF1aXdremlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTc1NDQsImV4cCI6MjA3MDAzMzU0NH0.RmDFOGu6reGp-pvbIcewYpdhyzH0ILDUvPYuxnOtJtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});